### ISSUE TITLE
Css don't have reload icon ...

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1424]
Hi,

Downloaded the latest zip. Noticed that : 
'reload'   : { type: 'button', id: 'w2ui-reload', icon: 'w2ui-icon-reload', tooltip: 'Reload data in the list' }, 
don't have in css . 

![reload](https://cloud.githubusercontent.com/assets/12154604/21303620/370bff92-c5c8-11e6-9899-6a007c9e6e4f.png)

With best regards ! :)

**Comment by mrg2001** [comment]
There was a bug like this because I have added a few icons to the font, and needed to remap in css. But I fixed it a week or so ago. It is pushed to the latest master. Where did you download zip from? Current master should be good with it.

**Comment by Rimokas** [comment]
At this moment ( some minutes ago ) I downloaded zip from here, github ... Still doesn't exist reload : 

![reload2](https://cloud.githubusercontent.com/assets/12154604/21312192/7b9b6316-c5f3-11e6-875d-738436fc6acb.png)

**Comment by mpf82** [comment]
Online it seems to work, both with the rc1 and the latest files:

http://w2ui.com/web/demos/#!grid/grid-3

http://jsfiddle.net/37d053aL/

**Comment by Rimokas** [comment]
Hmmm ... I pressed F5 some times, that was in workplace pc . Now I downloaded zip at home pc . Unziped and run the same demos - reload icon exist. All is working fine ... Thanks ! :)
