### ISSUE TITLE
Grid with selectType = Cell and scroll

### ISSUE THREAD

**Issue by ponyEdp** [vitmalina/w2ui#1890]
Good morning
If I set selectType = Cell in a grid.
After I scroll down the grid and I want type a text in a cell on the row number 7, for example, , automatically the grid focus go to the last row and the text (I'm typing) is inserted in the last row.
Watch the animated gif attached.
May you fix the problem ?
Do you want a JsFiddle example or I must post here the program code ?
Thanks
Best regards
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55495773/76735274-db307d00-6764-11ea-8627-cd504728bf3e.gif)

**Comment by vitmalina** [comment]
Can you please create a JS fiddle example as I am not following what the problem is?

**Comment by ponyEdp** [comment]
Good morning.
I solve the problem.
It was because I use jquery version 3.3.1 instead of jquery version 2.1.1
Regards

**Comment by shayolz** [comment]
Hello, we are having the same issue with selectType cell.

If we scroll on table and try to select something, the selected cell is shifted, like @ponyEdp showed.

This issue appear using Jquery > 3.2. @vitmalina Do you think is there any possibility to fix the problem on last version of jquery? We can't downgrade jquery atm.

You can easly test the issue here:
http://jsfiddle.net/skce016d/

HOW TO reproduce the error:

Scroll a little bit the table, then do a big select of 2-3 records and you will see that the selection is wrong. (While if you select jquery 3.2 there is no bug.)

**Comment by vitmalina** [comment]
It has been fixed in both branches, `master` and `w2ui-1.5`

**Comment by mpf82** [comment]
@vitmalina The issue still exists in the current master, as demonstrated in the linked demo above: http://jsfiddle.net/skce016d/

How to reproduce: scroll down a bit and the make a selection across all 3 columns.

![w2ui_issue_1890](https://user-images.githubusercontent.com/10152404/118566586-71e73800-b774-11eb-9ed2-42665fc80414.gif)

**Comment by mpf82** [comment]
Should be fixed, please re-open if the issue still exists.
